build:
  - .github/**/*

scripts:
  - buildSrc/src/main/kotlin/care/data4life/sdk/crypto/**/*.kts

dependencies:
  - buildSrc/**/*

documentation:
  - docs/**/*
  - README.adoc
  - LICENSE
  - CHANGELOG.adoc
  - CODE-OF-CONDUCT.adoc
  - CONTRIBUTION.adoc
  - readmeOSS.adoc

# Library
crypto:
  - crypto/**/*

# Sample Apps
sample-android:
  - sample-android/**/*
sample-jvm:
  - sample-jvm/**/*
